name: material_you
description: An flutter package for implementing the Material You design language
version: 0.0.21
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: any
  tuple: ">=1.0.0 <3.0.0"
  palette_from_wallpaper: ^0.1.5
  flutter_monet_theme: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
